metadata/graphs/sdg/__init__.py
from flask import Blueprint

sdg_app = Blueprint('sdg', __name__, template_folder='templates', static_folder='static', cli_group='sdg')

from metadata.graphs.sdg.commands import *

@sdg_app.route('/')
def index():
    return "foo"

metadata/sdg/__init__.py
from flask import Blueprint

sdg_app = Blueprint('sdg', __name__, template_folder='templates', static_folder='static')

from metadata.sdg import routes

metadata/sdg/routes.py
import re
from flask import render_template, request, abort, Response
from flask_accept import accept
from natsort import natsorted
from rdflib import Graph, RDF, RDFS, OWL, Namespace, URIRef
from rdflib.namespace import SKOS, DC, DCTERMS, FOAF, DOAP
from urllib.parse import quote, unquote, unquote_plus
from os.path import join, dirname, realpath
from metadata.lib.gsparql import build_graph, get_pref_label, SDGO, get_lexical_literal, fetch_external_label
from metadata.sdg import sdg_app
from metadata.sdg.config import Config

return_kwargs = {
    'title': Config.INIT['title']
}

def get_match_class_by_regex(match_classes, pattern):
    return(next(filter(lambda m: re.compile(m['id_regex']).match(pattern),match_classes), None))

def get_match_class_by_name(match_classes, name):
    return(next(filter(lambda m: m['name'] == name ,match_classes), None))

def get_preferred_language(request):
    pref_lang = request.args.get('lang', request.accept_languages.best_match(Config.LANGUAGES.keys()))
    if pref_lang is None:
        pref_lang = 'en'
    return pref_lang

endpoint = Config.spqarql_endpoint + Config.repository_name

@sdg_app.route('/')
@accept('text/html')
def index():
    lang = get_preferred_language(request)
    this_c = get_match_class_by_name(Config.match_classes,'Root')
    root_concept = build_graph(this_c['scheme_uri'], endpoint)

    return_data = {
        'prefLabel': get_pref_label(this_c['scheme_uri'], root_concept, lang),
        'goals': []
    }

    goals = natsorted([o for s, p, o in root_concept.triples((None, SKOS.hasTopConcept, None))])
    for goal in goals:
        goal_uri = goal.replace(Config.base_uri, Config.local_base_uri)
        return_data['goals'].append({
            'id': goal_uri.split('/')[-1].zfill(2),
            'uri': goal_uri
        })

    return render_template('sdg_index.html', data=return_data, lang=lang, site_lang=lang, **return_kwargs)

@sdg_app.route('/_expand')
@accept('text/html')
def _expand():
    lang = request.args.get('amp;lang', 'en')
    #print(f'For expansion, I have {lang}')
    rdf_type = request.args.get('amp;rdf_type')
    uri = unquote(request.args.get('uri'))
    this_id = request.args.get('amp;id')
    #print(uri)

    if rdf_type == 'goal':
        goal_graph = build_graph(uri, endpoint)
        goal = {}
        goal['gid'] = this_id
        goal['uri'] = uri
        goal['note'] = get_lexical_literal(uri, goal_graph, SKOS.note, lang)
        goal['prefLabel'] = get_pref_label(uri, goal_graph, lang)
        goal['altLabels'] = get_lexical_literal(uri, goal_graph, SKOS.altLabel, lang)
        goal['targets'] = []
        
        targets = natsorted([o for s,p,o in goal_graph.triples((None, SDGO.hasTarget, None))])
        for target in targets:
            goal['targets'].append({
                'id': target.split('/')[-1],
                'uri': target
            })

        #print(goal['targets'])

        return render_template('sdg__goal.html', goal=goal, lang=lang)
    elif rdf_type == 'target':
        target_graph = build_graph(uri, endpoint)
        target = {
            'id': uri.split('/')[-1],
            'uri': uri.replace(Config.base_uri, Config.local_base_uri),
            'note': get_lexical_literal(uri, target_graph, SKOS.note, lang),
            'prefLabel': get_pref_label(uri, target_graph, lang),
            'indicators': []
        }
        indicators = natsorted([o for s,p,o in target_graph.triples((None, SDGO.hasIndicator, None))])
        for indicator in indicators:
            #print(indicator)
            indicator_graph = build_graph(indicator, endpoint)
            target['indicators'].append({
                'id': uri.split('/')[-1],
                'uri': uri.replace(Config.base_uri, Config.local_base_uri),
                'note': get_lexical_literal(uri, indicator_graph, SKOS.note, lang),
                'prefLabel': get_pref_label(uri, indicator_graph, lang)
            })

        return render_template('sdg__target.html', target=target, lang=lang)
    else:
        pass

@sdg_app.route('/about')
@accept('text/html')
def about():
    lang = get_preferred_language(request)
    return render_template('sdg_about.html', lang=lang, site_lang=lang)

@sdg_app.route('/<id>')
@accept('text/html')
def get_concept(id):
    lang = get_preferred_language(request)
    uri = "/".join([Config.base_uri,str(id)])
    if re.match("^\d{1,2}$",id):
        return_data = get_goal(uri, lang)
    elif re.match("^\d{1,2}.[a-zA-Z0-9]{1,2}$", id):
        return_data = get_target(uri, lang)
    elif re.match("^C[a-zA-Z-0-9]{6,6}$", id):
        return_data = get_indicator(uri, lang)
    else:
        # Series patterns aren't as easily predictable, so it will be important to 
        # screen out bad attempts quickly and return a 404
        return_data = get_series(uri, lang)

    return render_template(return_data['template'], data=return_data, lang=lang, site_lang=lang, **return_kwargs)

def get_goal(uri, lang):
    graph = build_graph(uri, endpoint)
    if graph is None:
        abort(404)
    return_data = {
        'template': 'sdg_goal.html',
        'uri': uri.replace(Config.base_uri, Config.local_base_uri),
        'skos:prefLabel': get_pref_label(uri, graph, lang),
        'rdf:type': [{'uri': o, 'label': graph.qname(o)} for s,p,o in graph.triples((None, RDF.type, None)) if 'sdgo' in graph.qname(o)][0],
        'skos:note': get_lexical_literal(uri, graph, SKOS.note, lang),
        'skos:inScheme': [o for s,p,o in graph.triples((None, SKOS.inScheme, None))],
        'dct:subject': [],  # Empty so we can label it
        'sdgo:hasTarget': [],   # Empty so we can label it
        'skos:exactMatch': []
    }
    subjects = natsorted([o for s,p,o in graph.triples((None, DCTERMS.subject, None))])
    for subject in subjects:
        ext_label = fetch_external_label(subject, lang)
        return_data['dct:subject'].append({
            'uri': subject,
            'label': ext_label['label'],
            'source': ext_label['source']
        })
    targets = natsorted([o for s,p,o in graph.triples((None, SDGO.hasTarget, None))])
    for target in targets:
        target_graph = build_graph(target, endpoint)
        return_data['sdgo:hasTarget'].append({
            'uri': target,
            'note': get_lexical_literal(target, target_graph, SKOS.note, lang),
            'label': get_pref_label(target, target_graph, lang)
        })
    exact_matches = natsorted([o for s,p,o in graph.triples((None, SKOS.exactMatch, None))])
    for em in exact_matches:
        #print(em)
        ext_label = fetch_external_label(em, lang)
        
        #print(f'External label: {ext_label}')
        if ext_label is None:
            continue
        return_data['skos:exactMatch'].append({
            'uri': em,
            'label': ext_label['label'],
            'source': ext_label['source']
        })
    return return_data

def get_target(uri, lang):
    graph = build_graph(uri, endpoint)
    if graph is None:
        abort(404)
    return_data = {
        'template': 'sdg_target.html',
        'uri': uri.replace(Config.base_uri, Config.local_base_uri),
        'skos:prefLabel': get_pref_label(uri, graph, lang),
        'rdf:type': [{'uri': o, 'label': graph.qname(o)} for s,p,o in graph.triples((None, RDF.type, None)) if 'sdgo' in graph.qname(o)][0],
        'skos:note': get_lexical_literal(uri, graph, SKOS.note, lang),
        'skos:inScheme': [o for s,p,o in graph.triples((None, SKOS.inScheme, None))],
        'sdgo:isTargetOf': [],
        'dct:subject': [],  # Empty so we can label it
        'sdgo:hasIndicator': [],   # Empty so we can label it
    }
    goals = natsorted([o for s,p,o in graph.triples((None, SDGO.isTargetOf, None))])
    for goal in goals:
        goal_graph = build_graph(goal, endpoint)
        return_data['sdgo:isTargetOf'].append({
            'uri': goal,
            'note': get_lexical_literal(goal, goal_graph, SKOS.note, lang),
            'label': get_pref_label(goal, goal_graph, lang)
        })
    indicators = natsorted([o for s,p,o in graph.triples((None, SDGO.hasIndicator, None))])
    for indicator in indicators:
        indicator_graph = build_graph(indicator, endpoint)
        return_data['sdgo:hasIndicator'].append({
            'uri': indicator,
            'note': get_lexical_literal(indicator, indicator_graph, SKOS.note, lang),
            'label': get_pref_label(indicator, indicator_graph, lang)
        })
    subjects = natsorted([o for s,p,o in graph.triples((None, DCTERMS.subject, None))])
    for subject in subjects:
        ext_label = fetch_external_label(subject, lang)
        return_data['dct:subject'].append({
            'uri': subject,
            'label': ext_label['label'],
            'source': ext_label['source']
        })
    return return_data

def get_indicator(uri, lang):
    graph = build_graph(uri, endpoint)
    if graph is None:
        abort(404)
    return_data = {
        'template': 'sdg_indicator.html',
        'uri': uri.replace(Config.base_uri, Config.local_base_uri),
        'skos:prefLabel': get_pref_label(uri, graph, lang),
        'rdf:type': [{'uri': o, 'label': graph.qname(o)} for s,p,o in graph.triples((None, RDF.type, None)) if 'sdgo' in graph.qname(o)][0],
        'skos:note': get_lexical_literal(uri, graph, SKOS.note, lang),
        'skos:inScheme': [o for s,p,o in graph.triples((None, SKOS.inScheme, None))],
        'sdgo:tier': [o for s,p,o in graph.triples((None, SDGO.tier, None))],
        'sdgo:isIndicatorOf': [],
        'dct:subject': [],  # Empty so we can label it
        'sdgo:hasSeries': [],   # Empty so we can label it
    }
    targets = natsorted([o for s,p,o in graph.triples((None, SDGO.isIndicatorOf, None))])
    for target in targets:
        target_graph = build_graph(target, endpoint)
        return_data['sdgo:isIndicatorOf'].append({
            'uri': target,
            'note': get_lexical_literal(target, target_graph, SKOS.note, lang),

metadata/sdg/templates/sdg__goal.html
{% set gid = goal['gid'] %}
<div class="col-sm-12">
    <div class="row">
        <div class="col-1">
            <a id="target-collapser-{{gid}}" 
                class="plus-minus bc-link far fa-plus-square" 
                data-toggle="collapse" 
                href="#target-collapse-{{gid}}" 
                aria-expanded="false" 
                aria-controls="target-collapse-{{gid}}">
            </a>
        </div>
        <div class="col-sm-2">
            <a href="{{goal['uri']}}?lang={{lang}}" class="bc-link">{{ goal['note'] }}: {{ goal['altLabels'] }}</a>
        </div>
        <div class="col">
            <a href="{{goal['uri']}}?lang={{lang}}" class="bc-link">
            {{ goal['prefLabel']}}
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col">
            <div class="row mx-2 collapse hide" id="target-collapse-{{gid}}">
                <div class="col-sm-12" id="targets">
                    {% for target in goal['targets'] %}
                        {% set tid = target['id']|replace(".","") %}
                        <div class="row my-2" id="target-{{tid}}"></div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function() {
        $('a.plus-minus#target-collapser-{{gid}}').on('dblclick', function(event){
            $(this).toggleClass('fa-plus-square fa-minus-square');
        });
        $('a.plus-minus#target-collapser-{{gid}}').on('click', function(event) {
            $(this).toggleClass('fa-plus-square fa-minus-square');
            {% for target in goal['targets'] %}
                {% set tid = target['id']|replace(".","") %}
                $("#target-{{tid}}").load("{{url_for('sdg._expand',uri=target['uri'], rdf_type='target', lang=lang, id=target['id'])}}");
            {% endfor %}
        });
    });
</script>

metadata/sdg/templates/sdg__target.html
{% set tid = target['id']|replace(".","") %}
<div class="col-sm-12">
    <div class="row">
        <div class="col-1">
            <a id="indicator-collapser-{{tid}}" 
                class="plus-minus bc-link far fa-plus-square" 
                data-toggle="collapse" 
                href="#indicator-collapse-{{tid}}" 
                aria-expanded="false" 
                aria-controls="indicator-collapse-{{tid}}">
            </a>
        </div>
        <div class="col-sm-2">
            <a href="{{target['uri']}}?lang={{lang}}" class="bc-link">{{ target['note'] }}: </a>
        </div>
        <div class="col">
            <a href="{{target['uri']}}?lang={{lang}}" class="bc-link">
            {{ target['prefLabel'] }}
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col">
            <div class="row mx-2 collapse hide" id="indicator-collapse-{{tid}}">
                <div class="col-sm-12" id="goals">
                    {% for indicator in target['indicators'] %}
                        <div class="row my-2" id="indicator-{{indicator['id']}}">
                            <div class="col-sm-12">
                                <div class="row">
                                    <div class="col-1">
                                    </div>
                                    <div class="col-sm-2">
                                        <a href="{{indicator['uri']}}?lang={{lang}}" class="bc-link">{{ indicator['note'] }}: </a>
                                    </div>
                                    <div class="col">
                                        <a href="{{indicator['uri']}}?lang={{lang}}" class="bc-link">
                                        {{ indicator['prefLabel'] }}
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(function() {
    $('a.plus-minus#target-collapser-{{tid}}').on('dblclick', function(event){
            $(this).toggleClass('fa-plus-square fa-minus-square');
    });
    $('a.plus-minus#indicator-collapser-{{tid}}').on('dblclick', function(event){
            $(this).toggleClass('fa-plus-square fa-minus-square');
    });
    $('a.plus-minus#target-collapser-{{tid}}').on('click', function(event) {
        //console.log($(this));
        $(this).toggleClass('fa-plus-square fa-minus-square');
    });
    $('a.plus-minus#indicator-collapser-{{tid}}').on('click', function(event) {
        //console.log($(this));
        $(this).toggleClass('fa-plus-square fa-minus-square');
    });
});
</script>

metadata/sdg/templates/sdg_goal.html
{% extends 'sdg_base.html' %}
{% block container %}
<div class="container">
    <div class="col-sm-12">
        <div class="row my-2">
            <div class="col-sm-2">{{_('skos:prefLabel')}}</div>
            <div class="col-sm-9">{{data['skos:prefLabel']}}</div>
        </div>
        {% if data['rdf:type'] %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('rdf:type')}}</div>
            <div class="col-sm-9"><a class="bc-link" href="{{data['rdf:type']['uri']}}">{{data['rdf:type']['label']}}</a></div>
        </div>
        {% endif %}
        {% if data['skos:note'] %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('skos:note')}}</div>
            <div class="col-sm-9">
                <div class="row">
                    <div class="col">
                        {{data['skos:note']}}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('skos:inScheme')}}</div>
            <div class="col-sm-9">
                {% for inscheme in data['skos:inScheme'] %}
                <div class="row">
                    <div class="col-1"></div>
                    <div class="col">
                        <a class="bc-link" href="{{inscheme}}?lang={{lang}}">{{inscheme}}</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        {% if data['dct:subject'] and data['dct:subject']|length > 0 %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('dct:subject')}}</div>
            <div class="col-sm-9">
                {% for subject in data['dct:subject'] %}
                <div class="row">
                    <div class="col">
                        <a class="bc-link" href="{{subject['uri']}}?lang={{lang}}">{{subject['label']}}</a> (<a class="bc-link" href="{{subject['source']['uri']}}?lang={{lang}}">{{subject['source']['name']}}</a>)
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        <div class="row my-2">
            <div class="col-sm-2">{{_('sdgo:hasTarget')}}</div>
            <div class="col-sm-9">
                {% for target in data['sdgo:hasTarget'] %}
                <div class="row" style="margin-bottom: 10px;">
                    <div class="col">
                        <a class="bc-link" href="{{target['uri']}}?lang={{lang}}">{{target['note']}}: {{target['label']}}</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        
        {% if data['skos:exactMatch'] and data['skos:exactMatch']|length > 0 %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('skos:exactMatch')}}</div>
            <div class="col-sm-9">
                {% for subject in data['skos:exactMatch'] %}
                <div class="row">
                    <div class="col">
                        <a class="bc-link" href="{{subject['uri']}}?lang={{lang}}">{{subject['label']}}</a> (<a class="bc-link" href="{{subject['source']['uri']}}">{{subject['source']['name']}}</a>)
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('URI')}}</div>
            <div class="col-sm-9">{{data['uri']}}</div>
        </div>
    </div>
</div>
{% endblock %}

metadata/sdg/templates/sdg_index.html
{% extends 'sdg_base.html' %}
{% block container %}
    <div class="container">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-12">
                    <h3>{{data['prefLabel']}}</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12" id="goals">
                    {% for goal in data['goals'] %}
                        <div class="row my-2" id="goal-{{goal['id']}}"></div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(function() {
            {% for goal in data['goals'] %}
                $("#goal-{{goal['id']}}").load("{{url_for('sdg._expand',uri=goal['uri'], rdf_type='goal', lang=lang, id=goal['id'])}}");
            {% endfor %}
        });
    </script>
{% endblock %}

metadata/sdg/templates/sdg_indicator.html
{% extends 'sdg_base.html' %}
{% block container %}
<div class="container">
    <div class="col-sm-12">
        <div class="row my-2">
            <div class="col-sm-2">{{_('skos:prefLabel')}}</div>
            <div class="col-sm-9">{{data['skos:prefLabel']}}</div>
        </div>
        {% if data['rdf:type'] %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('rdf:type')}}</div>
            <div class="col-sm-9"><a class="bc-link" href="{{data['rdf:type']['uri']}}">{{data['rdf:type']['label']}}</a></div>
        </div>
        {% endif %}
        {% if data['skos:note'] %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('skos:note')}}</div>
            <div class="col-sm-9">
                <div class="row">
                    <div class="col">
                        {{data['skos:note']}}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('skos:inScheme')}}</div>
            <div class="col-sm-9">
                {% for inscheme in data['skos:inScheme'] %}
                <div class="row">
                    <div class="col-1"></div>
                    <div class="col">
                        <a class="bc-link" href="{{inscheme}}?lang={{lang}}">{{inscheme}}</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="row my-2">
            <div class="col-sm-2">{{_('sdgo:isIndicatorOf')}}</div>
            <div class="col-sm-9">
                {% for target in data['sdgo:isIndicatorOf'] %}
                <div class="row" style="margin-bottom: 10px;">
                    <div class="col">
                        <a class="bc-link" href="{{target['uri']}}?lang={{lang}}">{{target['note']}}: {{target['label']}}</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        {% if data['sdgo:tier'] and data['sdgo:tier']|length > 0 %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('sdgo:tier')}}</div>
            <div class="col-sm-9">
                {% for tier in data['sdgo:tier'] %}
                <div class="row">
                    <div class="col">
                        <a class="bc-link" href="{{tier}}">{{tier}}</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% if data['dct:subject'] and data['dct:subject']|length > 0 %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('dct:subject')}}</div>
            <div class="col-sm-9">
                {% for subject in data['dct:subject'] %}
                <div class="row">
                    <div class="col">
                        <a class="bc-link" href="{{subject['uri']}}?lang={{lang}}">{{subject['label']}}</a> (<a class="bc-link" href="{{subject['source']['uri']}}?lang={{lang}}">{{subject['source']['name']}}</a>)
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        
        {% if data['sdgo:hasSeries'] and data['sdgo:hasSeries']|length > 0 %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('sdgo:hasSeries')}}</div>
            <div class="col-sm-9">
                {% for target in data['sdgo:hasSeries'] %}
                <div class="row" style="margin-bottom: 10px;">
                    <div class="col">
                        <a class="bc-link" href="{{target['uri']}}?lang={{lang}}">{{target['label']}}</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        
        {% if data['skos:exactMatch'] and data['skos:exactMatch']|length > 0 %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('skos:exactMatch')}}</div>
            <div class="col-sm-9">
                {% for subject in data['skos:exactMatch'] %}
                <div class="row">
                    <div class="col">
                        <a class="bc-link" href="{{subject['uri']}}?lang={{lang}}">{{subject['label']}}</a> (<a class="bc-link" href="{{subject['source']['uri']}}">{{subject['source']['name']}}</a>)
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('URI')}}</div>
            <div class="col-sm-9">{{data['uri']}}</div>
        </div>
    </div>
</div>
{% endblock %}

metadata/sdg/templates/sdg_series.html
{% extends 'sdg_base.html' %}
{% block container %}
<div class="container">
    <div class="col-sm-12">
        <div class="row my-2">
            <div class="col-sm-2">{{_('skos:prefLabel')}}</div>
            <div class="col-sm-9">{{data['skos:prefLabel']}}</div>
        </div>
        {% if data['rdf:type'] %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('rdf:type')}}</div>
            <div class="col-sm-9"><a class="bc-link" href="{{data['rdf:type']['uri']}}">{{data['rdf:type']['label']}}</a></div>
        </div>
        {% endif %}
        {% if data['skos:note'] %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('skos:note')}}</div>
            <div class="col-sm-9">
                <div class="row">
                    <div class="col">
                        {{data['skos:note']}}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('skos:inScheme')}}</div>
            <div class="col-sm-9">
                {% for inscheme in data['skos:inScheme'] %}
                <div class="row">
                    <div class="col-1"></div>
                    <div class="col">
                        <a class="bc-link" href="{{inscheme}}?lang={{lang}}">{{inscheme}}</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="row my-2">
            <div class="col-sm-2">{{_('sdgo:isSeriesOf')}}</div>
            <div class="col-sm-9">
                {% for target in data['sdgo:isSeriesOf'] %}
                <div class="row" style="margin-bottom: 10px;">
                    <div class="col">
                        <a class="bc-link" href="{{target['uri']}}?lang={{lang}}">{{target['note']}}: {{target['label']}}</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        {% if data['sdgo:tier'] and data['sdgo:tier']|length > 0 %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('sdgo:tier')}}</div>
            <div class="col-sm-9">
                {% for tier in data['sdgo:tier'] %}
                <div class="row">
                    <div class="col">
                        <a class="bc-link" href="{{tier}}">{{tier}}</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% if data['dct:subject'] and data['dct:subject']|length > 0 %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('dct:subject')}}</div>
            <div class="col-sm-9">
                {% for subject in data['dct:subject'] %}
                <div class="row">
                    <div class="col">
                        <a class="bc-link" href="{{subject['uri']}}?lang={{lang}}">{{subject['label']}}</a> (<a class="bc-link" href="{{subject['source']['uri']}}?lang={{lang}}">{{subject['source']['name']}}</a>)
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        
        {% if data['skos:exactMatch'] and data['skos:exactMatch']|length > 0 %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('skos:exactMatch')}}</div>
            <div class="col-sm-9">
                {% for subject in data['skos:exactMatch'] %}
                <div class="row">
                    <div class="col">
                        <a class="bc-link" href="{{subject['uri']}}?lang={{lang}}">{{subject['label']}}</a> (<a class="bc-link" href="{{subject['source']['uri']}}">{{subject['source']['name']}}</a>)
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        <div class="row my-2">
            <div class="col-sm-2">{{_('URI')}}</div>
            <div class="col-sm-9">{{data['uri']}}</div>
        </div>
    </div>
</div>
{% endblock %}